import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "./ThemeRegistry";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "../app/utils/CommonStyles.css";
import Providers from "@/app/redux/Provider.js";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body>
        <ToastContainer />
        <Providers>
            <ThemeRegistry options={{ key: "mui-theme" }}>
                {children}
            </ThemeRegistry>
        </Providers>
        </body>
        </html>
    );
}
